<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.1 static/models/EbonyKey.glb --transform
-->

<script>
	import { T } from '@threlte/core';
	import { useGltf, useDraco } from '@threlte/extras';

	let { fallback, error, children, ref = $bindable(), ...props } = $props();

	const dracoLoader = useDraco();
	const gltf = useGltf('/EbonyKey-transformed.glb', { dracoLoader });
</script>

<T.Group bind:ref dispose={false} {...props}>
	{#await gltf}
		{@render fallback?.()}
	{:then gltf}
		<T.Mesh geometry={gltf.nodes.Sphere.geometry}>
			<T.MeshPhysicalMaterial
				color="hotpink"
				metalness={0.9}
				roughness={0.1}
				clearcoat={1.0}
				clearcoatRoughness={0.1}
				anisotropy={1.0}
				anisotropyRotation={0}
				envMapIntensity={1.0}
				reflectivity={1.0}
				sheen={1.0}
				sheenColor={0xffffff}
				sheenRoughness={0.3}
				iridescence={0.8}
				iridescenceIOR={1.3}
				iridescenceThicknessRange={[100, 800]}
			/>
		</T.Mesh>
	{:catch err}
		{@render error?.({ error: err })}
	{/await}

	{@render children?.({ ref })}
</T.Group>
